### ISSUE TITLE
Softwarelisten

### ISSUE THREAD

**Issue by nevrome** [chrinne/Softwarebox_DGUF#3]
Es gibt zwei schöne Softwarelisten von Ben Marwick und Zack Batist, auf die ggf. verwiesen werden kann:

CRAN Task View: Archaeological Science (für R): https://github.com/benmarwick/ctv-archaeology
Open Archaeology Software & Resources: https://github.com/zackbatist/open-archaeo

**Comment by chrinne** [comment]
cited, done
